version: '3'
services:
  app:
    image: autoker3
    ports:
      - "9090:8081"
    depends_on:
      - db
    links:
    - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    